### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by dlin8** [dlin8/Team-Rift#1]
Let's add a devlog.

**Comment by ghost** [comment]
I have added devlog.

**Comment by dlin8** [comment]
The devlog does not appear to be attached. Could you try again?

**Comment by ghost** [comment]
[Devlog.txt](https://github.com/dlin8/Team-Rift/files/82939/Devlog.txt)
Honya.

**Comment by dlin8** [comment]
Great work! Please push it to the repository.

**Comment by ghost** [comment]
I've.

**Comment by dlin8** [comment]
Thanks!
